services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - | 
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
#    depends_on:
#      - db
#  db:
#      image: postgres:latest
#      container_name: your-django-db
#      environment:
#        - POSTGRES_DB=yourdbname
#        - POSTGRES_USER=yourdbuser
#        - POSTGRES_PASSWORD=yourdbpassword
